resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [wp-blog]
    blog-wp.internal ansible_host=${yandex_compute_instance.wp.network_interface.0.nat_ip_address}
 
    DOC
  filename = "./ansible/inventory.ini"

  depends_on = [
    yandex_compute_instance.wp
  ]
}
